import type { Metadata } from "next";
import Link from "next/link";
import { ArticleUtilities } from "../../components/Listings";
import { ProjectCTA, ValidationNotice } from "../../components/Primitives";

export const metadata: Metadata = { title: "Préparer une étude de faisabilité : 7 questions structurantes", description: "Guide provisoire pour cadrer une étude de faisabilité et préparer les informations nécessaires." };
export default function ArticlePage() {
  const questions = [
    ["Quelle décision l’étude doit-elle éclairer ?", "Définir la décision attendue évite une étude trop large. Il peut s’agir de lancer, dimensionner, financer, phaser ou réorienter un projet."],
    ["Quel problème le projet cherche-t-il à résoudre ?", "La proposition de valeur doit être reliée à un besoin précis, à des bénéficiaires ou clients identifiables et à une solution réaliste."],
    ["Que savons-nous réellement du marché ?", "Les hypothèses de demande, de prix, de concurrence et d’accès au marché doivent être distinguées des informations déjà vérifiées."],
    ["Quelles options techniques faut-il comparer ?", "Capacité, localisation, technologie, calendrier et organisation influencent directement les coûts, les revenus et les risques."],
    ["Quel modèle économique est envisagé ?", "Il faut expliciter qui paie, pour quel service, à quel rythme, et quelles charges sont nécessaires pour délivrer cette valeur."],
    ["Quels sont les principaux risques ?", "Un registre initial des risques commerciaux, techniques, réglementaires, environnementaux et financiers aide à construire des scénarios utiles."],
    ["Quel financement et quel calendrier sont réalistes ?", "Le besoin de financement doit être relié au phasage, à la capacité de remboursement, aux apports disponibles et aux conditions des financeurs."],
  ];
  return <><ArticleUtilities /><article className="article-page"><header className="article-header"><div className="container"><Link href="/publications" className="back-link">← Retour aux publications</Link><div className="article-meta"><span>Guide pratique</span><span>Contenu éditorial provisoire</span><span>6 min</span></div><h1>Préparer une étude de faisabilité : <em>7 questions structurantes</em></h1><p>Un cadre de préparation pour clarifier le marché, les hypothèses, les risques et le besoin de financement avant de lancer l’étude.</p></div></header><div className="container article-layout"><aside><strong>Dans cette analyse</strong><ol>{questions.map(([title], index) => <li key={title}><a href={`#question-${index + 1}`}>{index + 1}. {title}</a></li>)}</ol><a className="download-card" href="/documents/guide-preparation-etude-faisabilite.pdf" download><span>PDF</span><div><strong>Télécharger le guide</strong><small>Version provisoire · 1 page</small></div></a></aside><div className="article-body"><ValidationNotice>Ce guide est un contenu pédagogique provisoire. Il ne constitue ni une étude de faisabilité, ni un conseil financier, juridique ou d’investissement adapté à une situation particulière.</ValidationNotice><p className="article-lead">Une étude de faisabilité est utile lorsqu’elle aide à prendre une décision. Sa qualité dépend autant de la méthode que de la clarté du cadrage initial.</p>{questions.map(([title, text], index) => <section id={`question-${index + 1}`} key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{text}</p>{index === 2 && <blockquote>Une hypothèse utile est une hypothèse explicite, sourcée et testable.</blockquote>}</section>)}<div className="article-conclusion"><h2>Avant de commencer</h2><p>Rassemblez les documents existants, identifiez les données manquantes et convenez des décisions que l’étude devra permettre de prendre. Le périmètre devient alors plus précis, le calendrier plus réaliste et le livrable plus utile.</p><Link className="button button-primary" href="/contact?demande=expertise">Cadrer une étude avec GEEF-SENEGAL</Link></div></div></div></article><ProjectCTA compact /></>;
}
