import type { Metadata } from "next";
import Link from "next/link";
import { PageHero, ProjectCTA, SectionHeading } from "../../components/Primitives";

const pages: Record<string, { eyebrow: string; title: string; intro: string; body: string }> = {
  home: { eyebrow: "GEEF-SENEGAL SARL", title: "Turning ambitious projects into sound, sustainable investments.", intro: "We support businesses, public institutions, investors and development partners in assessing, structuring, financing and delivering their projects.", body: "Financial Engineering & Economic Advisory Firm based in Dakar, Senegal." },
  about: { eyebrow: "About", title: "Local insight. Structured thinking. International outlook.", intro: "Discover the mission, vision and values that guide GEEF-SENEGAL.", body: "Our approach combines economic analysis, financial modelling, strategic advice and close collaboration with decision-makers." },
  expertise: { eyebrow: "Expertise", title: "From feasibility to financial structuring.", intro: "Economic studies, financial engineering, strategic advisory, training and technical assistance.", body: "Each engagement is designed around a clear decision, explicit assumptions and practical deliverables." },
  sectors: { eyebrow: "Sectors", title: "Sector knowledge makes financial analysis more relevant.", intro: "Financial services, energy, real estate, agribusiness, infrastructure and public institutions.", body: "We connect market, operational, regulatory and financial perspectives." },
  "case-studies": { eyebrow: "Case Studies", title: "Confidentiality, clarity and measurable methods.", intro: "Engagements are presented anonymously whenever client information cannot be disclosed.", body: "Results and impact are published only after formal validation." },
  insights: { eyebrow: "Insights", title: "Economic and financial perspectives.", intro: "A resource centre for analysis, market studies, practical guides and firm news.", body: "Explore practical perspectives designed for decision-makers, investors and project teams." },
  "our-team": { eyebrow: "Our Team", title: "Multidisciplinary expertise for complex decisions.", intro: "Finance, economics, project engineering, law and taxation can be combined for each engagement.", body: "Names, biographies and portraits are published only with formal approval." },
  training: { eyebrow: "Training", title: "Practical skills for stronger financial decisions.", intro: "In-person, online, in-company and tailored programmes.", body: "Programmes, trainers and dates will be confirmed for each session." },
  careers: { eyebrow: "Careers", title: "Bring your expertise to meaningful projects.", intro: "Jobs, internships, consultants and technical partners.", body: "No vacancy is presented as active until formally approved." },
  contact: { eyebrow: "Contact", title: "Start with a clear conversation.", intro: "Tell us about the context, decision and timeline for your project.", body: "Our team will guide you towards the appropriate next step." },
  "submit-a-project": { eyebrow: "Submit a Project", title: "Share the information needed to understand your ambition.", intro: "A confidential five-step process for an initial review.", body: "The full English submission form will be activated after legal and operational validation." },
};

export async function generateMetadata({ params }: { params: Promise<{ slug?: string[] }> }): Promise<Metadata> { const { slug } = await params; const key = slug?.[0] ?? "home"; const page = pages[key] ?? pages.home; return { title: `${page.eyebrow} — English`, description: page.intro, alternates: { languages: { "fr-SN": "/", en: `/en/${key === "home" ? "" : key}` } } }; }
export default async function EnglishStructurePage({ params }: { params: Promise<{ slug?: string[] }> }) { const { slug } = await params; const key = slug?.[0] ?? "home"; const page = pages[key] ?? pages.home; return <><PageHero eyebrow={page.eyebrow} title={page.title} intro={page.intro} image={key === "home" ? "/images/hero-team.webp" : undefined} alt="International team working in a modern professional environment."><Link className="button button-project" href="/en/contact">Contact GEEF-SENEGAL</Link></PageHero><section className="content-section is-white"><div className="container content-grid"><SectionHeading eyebrow="English version" title="A complete editorial structure, ready for approved translations." /><div className="content-copy"><p className="lead">{page.body}</p><p>This English section establishes the navigation, terminology and page architecture. Detailed content will be published only when each translation has been reviewed and approved.</p><div className="english-route-grid">{[["About", "about"], ["Expertise", "expertise"], ["Sectors", "sectors"], ["Case Studies", "case-studies"], ["Insights", "insights"], ["Our Team", "our-team"], ["Training", "training"], ["Careers", "careers"], ["Contact", "contact"], ["Submit a Project", "submit-a-project"]].map(([label, href]) => <Link key={href} href={`/en/${href}`}>{label}<span>↗</span></Link>)}</div></div></div></section><ProjectCTA compact /></>; }
